### ISSUE TITLE
These aren't indexed by Google

### ISSUE THREAD

**Issue by imkane** [s-yadav/react-meta-tags#17]
I did a test using Google Search Console to see how Googlebot crawls pages Node/React pages with these meta tags ... they don't work at all.

So this package is sort of useless ...

**Comment by annjawn** [comment]
I think this is specifically for Open Graph protocol for Social Graph (hence the `og`). This is useful for link shares of your app on social platforms like Facebook, Twitter, LinkedIn where the snipped would show up when you share a link. I am not sure how much helpful it would be for SEO.

**Comment by imkane** [comment]
But the 'title' and 'description' tags are also shown in the examples. These are detected by Google.

**Comment by s-yadav** [comment]
This is fixed

**Comment by imkane** [comment]
I don't see any changes, the HTML source still doesn't contain the Title and Description tags that we listed between <MetaTags</MetaTags>.

package-lock.json shows:
`"react-meta-tags": {
      "version": "0.4.2",`

Is there a more recent version?

**Comment by ThorinHanson** [comment]
> I don't see that this is fixed ... the HTML source still doesn't contain the Title and Description tags that we listed between <MetaTags.
> 
> package-lock.json shows:
> `"react-meta-tags": { "version": "0.4.2",`
> 
> Is there a more recent version?

I am having the same issue.  None of the og:<tags> are being rendered in the html source are are not being picked up by fb or linkedin.

**Comment by s-yadav** [comment]
Can you give example of how you are using it. Are you doing server side rendering?

**Comment by imkane** [comment]
We're using it exactly like you say to use it:
https://github.com/s-yadav/react-meta-tags#using-metatag-component

I don't understand why you'd recommend that method if there's no actual use for it. ie if browsers, search engine bots, etc don't actually detect the HTML meta tags because they don't actually show up in the HTML source.

I guess what I'm saying is ... what is the purpose of this package? From what I can tell it's useless. No offense, I'm just really confused.

**Comment by s-yadav** [comment]
@imkane I guess facebook crawlers can't parse client side javascript rendered site (Though need to confirm this). Google crawlers can do. The tags should come from server.  That's why there is server rendering example added. For client only site, I can't see how any of this type of library can help. You might have to setup a tool to serve a different page which crawlers can understand from the server side. There are lot of technique out there for it.
I will add that point on the doc.

`I guess what I'm saying is ... what is the purpose of this package? From what I can tell it's useless`
I feel you should learn to be little more polite and co operative with the contributors. You should find the problem and give a PR. 
If you don't like the library, no one is stopping you to use another library. Remember that most of the open source contributor are maintaining there libraries on their precious extra time.

**Comment by imkane** [comment]
> @imkane I guess facebook crawlers can't parse client side javascript rendered site (Though need to confirm this). **Google crawlers can do.** 

No, they don't. Read my initial comment. I tested this in Google Search Console. None of the meta tags are picked up by Googlebot.

Good luck, sorry that you don't like honest feedback.

**Comment by s-yadav** [comment]
@imkane Can you  try react-helmet (https://github.com/nfl/react-helmet). If that works for you then there is definitely some issue with this module. Let me know if it works for you.

I use it with few of production sites (where I do server rendering) and it works perfectly for google and facebook share. Also for SPA site I can see meta tags getting added correctly on head.  If you can set a codepen/fiddle I will be able to help you better.

**Comment by annjawn** [comment]
@imkane Google doesn't read Open Graph meta tags as far as I know mostly it doesn't need to. It does read other meta tags but provided your bundle has the proper `Robots.txt` and `sitemap.xml`. There are plenty of documents out there on how to setup meta tags for Google using some of the online google tools which will help you analyze if your meta tags are correct. Unlike the social media crawlers, Google bot now has the capability to crawl Javascript apps by first downloading the bundle, executing the javascript and then grab the information from the render. So yes, Google bot it quite advanced. I have been able to make meta tags work with Google without any issues in production for a serverless React app, BUT for `og:` meta tags things were different since FB/Twitter can't crawl SPA's the way GoogleBot does, so often time I found hard coding the `og:` tags right into my `index.html`. The only other way I found is using server side rendering (SSR), but mine was a serverless app and there was no server and thus I couldn't use SSR. In my opinion Helmet works best with apps that utilize SSR, I am not entirely sure if they have made any changes to support serverless apps (as in something like modify the `index.html` prior to or during bundling and deployment).

**Comment by imkane** [comment]
Yes, Helmet works - thanks!

> @imkane Can you try react-helmet (https://github.com/nfl/react-helmet). If that works for you then there is definitely some issue with this module. Let me know if it works for you.
> 
> I use it with few of production sites (where I do server rendering) and it works perfectly for google and facebook share. Also for SPA site I can see meta tags getting added correctly on head. If you can set a codepen/fiddle I will be able to help you better.
